export interface CharacterStats {
  might: number;        // % damage bonus (1.0 = 100%)
  armor: number;        // flat physical damage reduction
  maxHealth: number;    // maximum HP
  recovery: number;     // HP per second
  cooldown: number;     // attack cooldown multiplier (0.9 = 10% faster)
  area: number;         // AoE scale multiplier (1.0 = 100%)
  speed: number;        // projectile speed multiplier
  duration: number;     // projectile active duration multiplier
  amount: number;       // extra projectile count
  moveSpeed: number;    // character movement speed in px/s
  magnet: number;       // pickup attraction range in px
  luck: number;         // chance for 4th card, crits, better chests
  growth: number;       // XP multiplier (1.0 = 100%)
  greed: number;        // Gold multiplier (1.0 = 100%)
  curse: number;        // Enemy HP/speed multiplier
  revival: number;      // Extra lives
  rerolls: number;      // Level-up card reroll count
}

export interface HeroConfig {
  id: string;
  name: string;
  title: string;
  description: string;
  startingWeaponId: string;
  baseStats: CharacterStats;
  traitDescription: string;
  color: string;
  accentColor: string;
  spriteId: string;
}

export const HEROES: HeroConfig[] = [
  {
    id: 'valerius',
    name: 'Valerius',
    title: 'Abyssal Warden',
    description: 'Heavy armor and iron will, tainted by the deep void. Wields the Abyssal Edge.',
    startingWeaponId: 'whip',
    traitDescription: 'Gains +1 permanent Void Armor every 10 levels.',
    color: '#4f46e5',
    accentColor: '#818cf8',
    spriteId: 'hero_valerius',
    baseStats: {
      might: 1.0,
      armor: 1,
      maxHealth: 120,
      recovery: 0.5,
      cooldown: 1.0,
      area: 1.0,
      speed: 1.0,
      duration: 1.0,
      amount: 0,
      moveSpeed: 145,
      magnet: 80,
      luck: 1.0,
      growth: 1.0,
      greed: 1.0,
      curse: 1.0,
      revival: 0,
      rerolls: 1,
    },
  },
  {
    id: 'sylvia',
    name: 'Sylvia',
    title: 'Astral Occultist',
    description: 'Communes with outer cosmic entities to cast piercing void darts.',
    startingWeaponId: 'magic_wand',
    traitDescription: 'Adds +1 Void Projectile Amount to all weapons every 20 levels.',
    color: '#06b6d4',
    accentColor: '#67e8f9',
    spriteId: 'hero_sylvia',
    baseStats: {
      might: 1.0,
      armor: 0,
      maxHealth: 90,
      recovery: 0,
      cooldown: 0.85,
      area: 1.2,
      speed: 1.0,
      duration: 1.0,
      amount: 0,
      moveSpeed: 150,
      magnet: 90,
      luck: 1.1,
      growth: 1.05,
      greed: 1.0,
      curse: 1.0,
      revival: 0,
      rerolls: 2,
    },
  },
  {
    id: 'ignis',
    name: 'Ignis',
    title: 'Blackfire Pyromancer',
    description: 'Harnesses cursed blackfire from dead stars to incinerate cosmic horrors.',
    startingWeaponId: 'fire_wand',
    traitDescription: 'Critical strikes ignite monstrosities with abyssal blackfire (+50% burn).',
    color: '#c026d3',
    accentColor: '#e879f9',
    spriteId: 'hero_ignis',
    baseStats: {
      might: 1.2,
      armor: 0,
      maxHealth: 100,
      recovery: 0,
      cooldown: 1.1,
      area: 1.15,
      speed: 0.9,
      duration: 1.0,
      amount: 0,
      moveSpeed: 140,
      magnet: 75,
      luck: 1.15,
      growth: 1.0,
      greed: 1.0,
      curse: 1.0,
      revival: 0,
      rerolls: 1,
    },
  },
  {
    id: 'kaelen',
    name: 'Kaelen',
    title: 'Void Stalker',
    description: 'Cultist rogue slipping through spatial rifts with deadly obsidian fangs.',
    startingWeaponId: 'knife',
    traitDescription: 'Slips into the void gaining +40% Movement Speed when below 30% health.',
    color: '#059669',
    accentColor: '#34d399',
    spriteId: 'hero_kaelen',
    baseStats: {
      might: 0.9,
      armor: 0,
      maxHealth: 85,
      recovery: 0,
      cooldown: 0.9,
      area: 0.9,
      speed: 1.3,
      duration: 1.0,
      amount: 1,
      moveSpeed: 175,
      magnet: 85,
      luck: 1.2,
      growth: 1.0,
      greed: 1.1,
      curse: 1.0,
      revival: 0,
      rerolls: 2,
    },
  },
  {
    id: 'mortimer',
    name: 'Mortimer',
    title: 'Necro-Alchemist',
    description: 'Former scholar of Miskatonic delving into forbidden resurrection arts.',
    startingWeaponId: 'bone',
    traitDescription: 'Infuses projectiles with cosmic inertia (+20% projectile duration).',
    color: '#7c3aed',
    accentColor: '#c084fc',
    spriteId: 'hero_mortimer',
    baseStats: {
      might: 1.0,
      armor: 0,
      maxHealth: 95,
      recovery: 0.2,
      cooldown: 1.0,
      area: 1.0,
      speed: 1.0,
      duration: 1.2,
      amount: 0,
      moveSpeed: 148,
      magnet: 100,
      luck: 1.0,
      growth: 1.1,
      greed: 1.15,
      curse: 1.05,
      revival: 1,
      rerolls: 1,
    },
  },
  {
    id: 'nyx',
    name: 'Nyx',
    title: 'The Eldritch Weaver',
    description: 'Blind priestess weaving antimatter threads and dimensional silk to ensnare horrors.',
    startingWeaponId: 'void_tendril',
    traitDescription: 'Void Cocoon: Standing still for 1.2s spins a slowing silk web that increases damage by +25%.',
    color: '#8b5cf6',
    accentColor: '#a78bfa',
    spriteId: 'hero_nyx',
    baseStats: {
      might: 1.1,
      armor: 0,
      maxHealth: 100,
      recovery: 0.1,
      cooldown: 0.95,
      area: 1.1,
      speed: 1.0,
      duration: 1.25,
      amount: 0,
      moveSpeed: 152,
      magnet: 95,
      luck: 1.1,
      growth: 1.05,
      greed: 1.0,
      curse: 1.0,
      revival: 0,
      rerolls: 2,
    },
  },
  {
    id: 'malakor',
    name: 'Malakor',
    title: 'Drowned Inquisitor',
    description: 'Resurrected inquisitor dragged from the abyssal depths wielding a massive rust-caked anchor.',
    startingWeaponId: 'abyssal_anchor',
    traitDescription: 'Crushing Depths: Starts with +3 Armor and +50% Knockback. Shatters enemy defenses on impact.',
    color: '#0e7490',
    accentColor: '#38bdf8',
    spriteId: 'hero_malakor',
    baseStats: {
      might: 1.25,
      armor: 3,
      maxHealth: 150,
      recovery: 0.4,
      cooldown: 1.15,
      area: 1.2,
      speed: 0.9,
      duration: 1.0,
      amount: 0,
      moveSpeed: 135,
      magnet: 70,
      luck: 0.9,
      growth: 0.95,
      greed: 1.05,
      curse: 1.1,
      revival: 0,
      rerolls: 1,
    },
  },
  {
    id: 'morrigan',
    name: 'Morrigan',
    title: 'Sanguine Priestess',
    description: 'Dark cultist feeding upon vital ichor to perform forbidden blood transmutation rites.',
    startingWeaponId: 'blood_chalice',
    traitDescription: 'Blood Tithe: Sacrifices 10% max HP every minute to gain permanent +5% Might and +1% Lifesteal.',
    color: '#be123c',
    accentColor: '#f43f5e',
    spriteId: 'hero_morrigan',
    baseStats: {
      might: 1.15,
      armor: 1,
      maxHealth: 110,
      recovery: 0.8,
      cooldown: 1.0,
      area: 1.1,
      speed: 1.05,
      duration: 1.1,
      amount: 0,
      moveSpeed: 150,
      magnet: 85,
      luck: 1.2,
      growth: 1.0,
      greed: 1.2,
      curse: 1.15,
      revival: 0,
      rerolls: 2,
    },
  },
  {
    id: 'zephyr',
    name: 'Zephyr',
    title: 'Astral Astromancer',
    description: 'Mad astronomer whose eyes witnessed the cosmic singularity beyond the stars.',
    startingWeaponId: 'singularity_orb',
    traitDescription: 'Gravitational Core: +60% Magnet Range; vacuuming gems triggers gravitational shockwaves.',
    color: '#0284c7',
    accentColor: '#7dd3fc',
    spriteId: 'hero_zephyr',
    baseStats: {
      might: 1.05,
      armor: 0,
      maxHealth: 90,
      recovery: 0,
      cooldown: 0.9,
      area: 1.25,
      speed: 1.15,
      duration: 1.2,
      amount: 0,
      moveSpeed: 160,
      magnet: 160,
      luck: 1.3,
      growth: 1.2,
      greed: 1.0,
      curse: 1.05,
      revival: 0,
      rerolls: 3,
    },
  },
];
